services:
  backend:
    build:
      context: ./app
      dockerfile: ./Dockerfile
    volumes:
      - ./app/.env:/app/.env
    ports:
      - 8020:8000
    networks:
      - my_network

  frontend:
    build:
      context: ./ui
      dockerfile: ./Dockerfile
    ports:
      - 5173:5173
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
