[project]
name = "fosscu-subdomain-checker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests>=2.32.3",
    "fastapi[standard]>=0.115.4",
    "pydantic-settings>=2.6.0",
    "slowapi>=0.1.9",
]
